#!/usr/bin/env python3
"""
Update requirements for modern PowerlineUnet.
This script updates dependencies to modern versions while maintaining compatibility.
"""
import sys
from pathlib import Path

def update_requirements():
    """Update requirements.txt with modern versions."""
    
    modern_requirements = [
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "torchaudio>=2.1.0",
        "albumentations>=1.4.0",
        "opencv-python-headless>=4.8.0",
        "pillow>=10.0.0",
        "numpy>=1.24.0,<2.0.0",  # Avoid numpy 2.0 compatibility issues
        "matplotlib>=3.7.0",
        "pyyaml>=6.0.0",
        "tqdm>=4.65.0",
        "segmentation-models-pytorch>=0.3.3",
        "scikit-image>=0.21.0",
        "pandas>=2.0.0",
    ]
    
    dev_requirements = [
        "black>=23.0.0",
        "isort>=5.12.0",
        "ruff>=0.1.0",
        "pytest>=7.0.0",
        "pyyaml>=6.0.0",
    ]
    
    # Write main requirements
    with open("requirements.txt", "w") as f:
        f.write("# PowerlineUnet Dependencies\n")
        f.write("# Generated by update_requirements.py\n\n")
        for req in modern_requirements:
            f.write(f"{req}\n")
    
    # Write development requirements
    with open("requirements-dev.txt", "w") as f:
        f.write("# Development Dependencies\n")
        f.write("# Install with: pip install -r requirements-dev.txt\n\n")
        for req in dev_requirements:
            f.write(f"{req}\n")
    
    print("Requirements updated successfully!")
    print("Created:")
    print("   - requirements.txt (modern dependencies)")
    print("   - requirements-dev.txt (development tools)")
    print("\nNext steps:")
    print("   1. pip install -r requirements.txt")
    print("   2. pip install -e .  (for package development)")
    print("   3. Continue with code migration")


def create_setup_py():
    """Create setup.py for package installation."""
    setup_content = '''from setuptools import setup, find_packages

setup(
    name="powerline-unet",
    version="0.2.0",
    packages=find_packages(),
    install_requires=[
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "albumentations>=1.4.0",
        "opencv-python-headless>=4.8.0",
        "pillow>=10.0.0",
        "numpy>=1.24.0,<2.0.0",
        "pyyaml>=6.0.0",
    ],
    python_requires=">=3.10",
    author="Mark Hocking",
    author_email="hockma1985@gmail.com",
    description="U-Net for power line segmentation from drone imagery",
)
'''
    with open("setup.py", "w") as f:
        f.write(setup_content)
    print("Created setup.py for package installation")


if __name__ == "__main__":
    print("Updating PowerlineUnet dependencies...")
    update_requirements()
    create_setup_py()
    print("Requirements modernization complete!")
